name:                Tetris
version:             0.1.0.0
github:              "kamel2700/haskellTetris"
license:             BSD3
author:              Vyacheslav Vasilev & Kamil Alimov
maintainer:          v.vasilev@innopolis.ru & k.alimov@innopolis.ru
copyright:           2020 Vyacheslav Vasilev & Kamil Alimov

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kamel2700/haskellTetris#readme>

dependencies:
  - base >= 4.8 && < 5
  - gloss >= 1.12.0.0
  - random >= 1.1
#  - extra >= 1.7.8


library:
  source-dirs: src

executables:
  Tetris-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-type-defaults
    - -fdefer-typed-holes
    - -fshow-hole-constraints
    - -funclutter-valid-hole-fits
    dependencies:
    - Tetris
    - gloss
    - random

tests:
  Tetris-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-type-defaults
    - -fdefer-typed-holes
    - -fshow-hole-constraints
    - -funclutter-valid-hole-fits
    dependencies:
    - Tetris
    - gloss
    - random
