resolver: lts-16.16

packages:
- .

extra-deps:
  - gloss-1.13.1.2

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
